baseURL = "http://example.org/"
languageCode = "en-us"
title = "LeetCode Problems"
theme = "book"

# to allow <iframe>
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  BookTheme = 'auto'